### ISSUE TITLE
what os ?

### ISSUE THREAD

**Issue by tuteming** [marcoschwartz/meteor-aREST-mqtt#2]
Can you tell me
you run "meteor-aREST-mqtt" in what machine os?
I can not run in win 10 64 bit.
thanks

**Comment by marcoschwartz** [comment]
I tested it on my own machine (OS X 10.11), and cloud.arest.io is running on Ubuntu 14.10. Never tried it on Windows.

**Comment by tuteming** [comment]
Thanks
2015年11月30日 下午11:44於 "marcoschwartz" notifications@github.com寫道：

**Comment by flidget** [comment]
Not sure this is the correct repository. I can not install the aRest code for meteor v1.4.1 due to errors. Steps to reproduce: Install Meteor (1.4.1) and node.js (v4.4.7) on Mac (OS X 10.11.6).  Install  marcoschwartz:arest

server04:eden administrator$ meteor add marcoschwartz:arest
=> Errors while adding packages:
While downloading fourquet:serialport@2.0.6_1...:
error: Command failed:
/Users/administrator/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8+
+os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/
bin/npm
rebuild --no-bin-links --update-binary
module.js:327
throw err;
^
Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(/private/var/folders/v2/btcmwx3531n20xg6dtxjmgvh0000gn/T/mt-bkr311/
npm/node_modules/.temp-1sbxwct/node_modules/serialport/
node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/administrator/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8+
+os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/
bin/node"
"/Users/administrator/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8+
+os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/
bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! serialport@2.0.6 install: `node-pre-gyp install --fallbackto-
build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@2.0.6 install script 'node-pre-gyp
install
--fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm
installed.
npm ERR! If you do, this is most likely a problem with the
serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this
project with:
npm ERR! npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls serialport
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!
/private/var/folders/v2/btcmwx3531n20xg6dtxjmgvh0000gn/T/mt-bkr311/
npm/node_modules/.temp-1sbxwct/npm-debug.log
module.js:327
throw err;
^
Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(/private/var/folders/v2/btcmwx3531n20xg6dtxjmgvh0000gn/T/mt-bkr311/
npm/node_modules/.temp-1sbxwct/node_modules/serialport/
node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/administrator/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8+
+os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/
bin/node"
"/Users/administrator/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8+
+os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/
bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! serialport@2.0.6 install: `node-pre-gyp install --fallbackto-
build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@2.0.6 install script 'node-pre-gyp
install
--fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm
installed.
npm ERR! If you do, this is most likely a problem with the
serialport package,
npm ERR! not with npm itself.
